### ISSUE TITLE
Fails to build with OpenSSL 4.0.0

### ISSUE THREAD

**Issue by RolandRosenfeld** [xymon-monitoring/xymon#143]
I received a Debian bug report, that xymon does not build with OpenSSL 4.0.0: https://bugs.debian.org/1139228

I can reproduce the issue with current GIT HEAD:
```
make[1]: Entering directory '/usr/local/src/Packages/xymon/xymon.roro/xymonnet'
gcc -g -O2 -Wall -Wno-unused -I/usr/include/tirpc -Wno-pointer-sign -D_REENTRANT -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DLINUX -I/usr/local/src/Packages/xymon/xymon.roro/include  -DHAVE_OPENSSL  -c -o contest.o contest.c
contest.c: In function 'xymon_ASN1_UTCTIME':
contest.c:409:15: error: invalid use of incomplete typedef 'ASN1_UTCTIME' {aka 'struct asn1_string_st'}
  409 |         len=tm->length;
      |               ^~
contest.c:410:31: error: invalid use of incomplete typedef 'ASN1_UTCTIME' {aka 'struct asn1_string_st'}
  410 |         asn1_string=(char *)tm->data;
      |                               ^~
make[1]: *** [Makefile:51: contest.o] Error 1
make[1]: Leaving directory '/usr/local/src/Packages/xymon/xymon.roro/xymonnet'
```
