### PR TITLE
xymonnet: build against OpenSSL 4.0

### LINKED ISSUE #143: Fails to build with OpenSSL 4.0.0
I received a Debian bug report, that xymon does not build with OpenSSL 4.0.0: https://bugs.debian.org/1139228

I can reproduce the issue with current GIT HEAD:
```
make[1]: Entering directory '/usr/local/src/Packages/xymon/xymon.roro/xymonnet'
gcc -g -O2 -Wall -Wno-unused -I/usr/include/tirpc -Wno-pointer-sign -D_REENTRANT -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DLINUX -I/usr/local/src/Packages/xymon/xymon.roro/include  -DHAVE_OPENSSL  -c -o contest.o contest.c
contest.c: In function 'xymon_ASN1_UTCTIME':
contest.c:409:15: error: invalid use of incomplete typedef 'ASN1_UTCTIME' {aka 'struct asn1_string_st'}
  409 |         len=tm->length;
      |               ^~
contest.c:410:31: error: invalid use of incomplete typedef 'ASN1_UTCTIME' {aka 'struct asn1_string_st'}
  410 |         asn1_string=(char *)tm->data;
      |                               ^~
make[1]: *** [Makefile:51: contest.o] Error 1
make[1]: Leaving directory '/usr/local/src/Packages/xymon/xymon.roro/xymonnet'
```

### PR DESCRIPTION
**Pull request by bonomani**
## Summary

- use the public ASN.1 string accessors with OpenSSL 1.1.0 and later
- retain direct structure access for older supported OpenSSL releases
- fix the mismatched include guard in `xymonnet/httptest.h`

## Root cause

OpenSSL 4.0 makes `ASN1_STRING` opaque, so direct access to
`ASN1_UTCTIME` members no longer compiles. This caused the build failure
reported in issue #143 and Debian bug #1139228.

## Impact

`xymonnet` builds against OpenSSL 4.0 while preserving compatibility with
older OpenSSL versions.

## Validation

- compiled `xymonnet/contest.c` with Ubuntu OpenSSL 3.0.2 headers
- compiled `xymonnet/contest.c` and `xymonnet/httptest.c` with Debian
  experimental OpenSSL 4.0.0-1 headers
- confirmed `upstream/main` reproduces the incomplete `ASN1_UTCTIME` build
  error with the same OpenSSL 4.0 headers
- ran `git diff --check`

Closes #143

### CODE REVIEW

**Comment by bonomani** [comment]
Follow-up: once #101 is merged and the `tests` workflow is available on `main`, update this branch to trigger the new regression test suite against this change. The existing build checks are green, and compilation with Debian experimental OpenSSL 4.0.0-1 headers was also validated locally.

**Review by RolandRosenfeld — APPROVED** [review]
The code looks good to me and at least the sslcert test on Debian trixie (with OpenSSL 3.5.6), which uses the new code shows the correct dates.
